name: easy_dropdown2
description: EasyDropdown is a Flutter library for creating customizable and user-friendly dropdown menus with flexible positioning and styling.
version: 1.3.1
homepage: https://github.com/rjs580/easy_dropdown
repository: https://github.com/rjs580/easy_dropdown
issue_tracker: https://github.com/rjs580/easy_dropdown/issues
documentation: https://pub.dev/documentation/easy_dropdown2/latest/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
